CREATE TABLE IF NOT EXISTS songs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    artist TEXT NOT NULL,
    date_of_entry DATETIME DEFAULT CURRENT_TIMESTAMP,
    file_path TEXT NOT NULL
);
